=== Strivema/XML/xml/hi.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT scores (student+)>
	<!ELEMENT student (name,gender,score,course)>
	<!ATTLIST student id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT gender (#PCDATA)>
	<!ELEMENT score (#PCDATA)>
	<!ELEMENT course (#PCDATA)>

=== Strivema/XML/xml/hello.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- hello -->
<!DOCTYPE scores SYSTEM "hi.dtd">
<scores>
<student id="101">
	<name>Bob</name>
	<gender>male</gender>
	<score>80</score>
	<course>java</course>	
</student>
<student id="102">
	<name>Mary</name>
	<gender>female</gender>
	<score>80</score>
	<course>java</course>	
</student>

</scores>
